name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: node:12

    steps:
    - uses: actions/checkout@v1
    - name: show ip
      run:
        ip addr
    - name: Run a multi-line script
      run: |
        npm install
        node index.js
